In [1]:
#1. Write a NumPy program to print the NumPy version in your system.

import numpy as np
np.__version__

'1.16.2'

In [ ]:
#2. Write a NumPy program to convert a list of numeric value into a one-dimensional NumPy array.

a=[12.22,3.28,55,44]
np.array(a)

In [ ]:
#3.Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

np.matrix(np.arange(2,11).reshape(3,3))

In [ ]:
#4. Write a NumPy program to create a null vector of size 10 and update sixth value to 11.

a=np.zeros(10)
a[6]=11
a

In [ ]:
#5. Write a NumPy program to create a array with values ranging from 12 to 38.

np.arange(12,38)

In [ ]:
#6. Write a NumPy program to reverse an array (first element becomes last).

a=np.arange(12,38)
a[::-1]

In [ ]:
#7. Write a NumPy program to an array converted to a float type.

a=np.array([1,2,3,4])
a
np.asfarray(a)

In [ ]:
#8. Write a NumPy program to create a 2d array with 1 on the border and 0 inside.

a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
a[::3]=a[:,::3]=1
a[1:-1,1:-1]=0
a

In [3]:
#9. Write a NumPy program to add a border (filled with 0's) around an existing array.
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
# x=[[0,0,0,0]]
# y=[[0],[0],[0],[0],[0],[0]]
# arr=np.vstack((arr,x))
# arr=np.vstack((x,arr))
# arr
# arr=np.hstack((y,arr))
# arr=np.hstack((arr,y))
# arr
np.pad(arr,1,'constant')

array([[ 0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  0],
       [ 0,  5,  6,  7,  8,  0],
       [ 0,  9, 10, 11, 12,  0],
       [ 0, 13, 14, 15, 16,  0],
       [ 0,  0,  0,  0,  0,  0]])

In [4]:
#10. Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.
arr=np.arange(64).reshape(8,8)
arr[::2,::2]=arr[1::2,1::2]=0
arr[1::2,::2]=arr[::2,1::2]=1
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [ ]:
#11. Write a NumPy program to convert a list and tuple into arrays.
l=[1,2,3,4,5,6]
t=((8,6,5),(3,6,3))

a=np.asarray(l)
print(a)
b=np.asarray(t)
print(b)

In [ ]:
#12. Write a NumPy program to append values to the end of an array.

a=np.array([10,20,30,40])
np.append(a,[[50,60,70],[80,90,100]])


In [ ]:
#13. Write a NumPy program to create an empty and a full array.

print(np.empty((3,4)))
print(np.full((3,3),6))

In [ ]:
#14. Write a NumPy program to convert the values of Centigrade degrees into Fahrenheit degrees.
# Centigrade values are stored into a NumPy array.

c=np.array([0,25,50,75,100])
f=c*9/5+32
print(f)
c2=(f-32)*5/9
print(c2)

In [ ]:
#15. Write a NumPy program to find the real and imaginary parts of an array of complex numbers.

a=np.array([2,3+0j,9j,2+5j,np.nan,np.inf])
print(a)
print(a.real)
print(a.imag)

In [ ]:
#16. Write a NumPy program to find the number of elements of an array, length of one array element in bytes 
# and total bytes consumed by the elements.

a=np.array([2,3+0j,9j,2+5j,np.nan,np.inf])
print(a.size)
print(a.itemsize)
print(a.nbytes)

In [ ]:
#17. Write a NumPy program to test whether each element of a 1-D array is also present in a second array.

a=np.array([1,2,3,4,5,6])
b=np.array([1,2,3,4])
# [True if i in b else False for i in a]
np.in1d(a,b)

In [ ]:
#18. Write a NumPy program to find common values between two arrays.

a=np.array([1,2,3,4,5,6])
b=np.array([1,2,3,4])
np.intersect1d(a,b)

In [ ]:
#19. Write a NumPy program to get the unique elements of an array.

a=np.array([10,20,30,30,10,20,20,30,10])
print(np.unique(a))
b=np.array([[1,2],[1,3]])
print(np.unique(b))

In [ ]:
#20. Write a NumPy program to find the set difference of two arrays. The set difference will return the sorted, 
# unique values in array1 that are not in array2.

a=np.array([0,10,20,40,60,80])
b=np.array([10,30,40,70,90])
np.setdiff1d(a,b)

In [ ]:
#21. Write a NumPy program to find the set exclusive-or of two arrays. Set exclusive-or will return the sorted, 
# unique values that are in only one (not both) of the input arrays.

a=np.array([0,10,20,40,60,80])
b=np.array([10,30,40,70,90])
np.setxor1d(a,b)

In [ ]:
#22. Write a NumPy program to find the union of two arrays. Union will return the unique, 
# sorted array of values that are in either of the two input arrays.

a=np.array([0,10,20,40,60,80])
b=np.array([10,30,40,70,90])
np.union1d(a,b)

In [ ]:
#23. Write a NumPy program to test if all elements in an array evaluate to True.

a=np.array([0,10,20,40,60,80])
b=np.array([10,30,40,70,90])
c=np.array([np.nan,30,40,70,90])
d=np.array([False,30,40,70,90])


print(all(a))
print(all(b))
print(all(c))
print(all(d))

In [ ]:
#24. Write a NumPy program to test whether any array element along a given axis evaluates to True.

a=np.array([[0,10,20],[0,np.nan,80],[False,0,False]])
print(a.any(axis=0))
print(a.any(axis=1))

In [ ]:
#25. Write a NumPy program to construct an array by repeating.

a=np.array([1,2,3,4])
np.tile(a,3)

In [ ]:
#26. Write a NumPy program to repeat elements of an array.

a=np.array([1,2,3,4])
np.repeat(a,3)

In [ ]:
#27. Write a NumPy program to find the indices of the maximum and minimum values along the given axis of an array.

a=np.array([[8,6,3],[4,5,6],[7,4,9]])
print(a)
print(np.max(a,axis=0))
print(np.argmax(a,axis=0))
print(np.max(a,axis=1))
print(np.argmax(a,axis=1))

In [ ]:
#28. Write a NumPy program compare two arrays using numpy.

a=np.array([[1,2],[2,3]])
b=np.array([[2,3],[1,4]])
print(a>=b)
np.greater_equal(a,b)

In [ ]:
#29. Write a NumPy program to sort an along the first, last axis of an array.

b=np.array([[2,3,4],[1,2,4],[3,4,2]])
print(b)
print(np.sort(b,axis=0))
print(np.sort(b,axis=1))


In [ ]:
#30. Write a NumPy program to sort pairs of first name and last name return their indices. 
# (first by last name, then by first name).


first_names = ('Betsey', 'Shelley', 'Lanell', 'Genesis', 'Margery')
last_names = ('Battle', 'Brien', 'Plotner', 'Stahl', 'Woolum')
np.lexsort((first_names,last_names))   # (first by last name, then by first name)


In [ ]:
#31. Write a NumPy program to get the values and indices of the elements that are bigger than 10 in a given array.

a=np.array([[5,15,30,8],[11,10,4,25]])
print(a[a>10])
np.nonzero(a>10)

In [ ]:
#32. Write a NumPy program to save a NumPy array to a text file.

a=np.array([[5,15,30,8],[11,10,4,25]])
np.savetxt('temp1',a)

In [ ]:
#33. Write a NumPy program to find the memory size of a NumPy array.

a=np.array([[5,15,30,8],[11,10,4,25]])
a.nbytes

In [ ]:
#34. Write a NumPy program to create an array of ones and an array of zeros.

print(np.ones((3,3)))
print(np.zeros((3,3),dtype=np.int))

In [ ]:
#35. Write a NumPy program to change the dimension of an array.

a=np.arange(9)
print(a)
print(a.ndim)
print(a.shape)
a.shape=(3,3)
print(a)
print(a.ndim)

In [ ]:
#36. Write a NumPy program to create a contiguous flattened array.

a=np.array([[10,20,30],[20,40,50]])
a.ravel()

In [ ]:
#37. Write a NumPy program to create a 2-dimensional array of size 2 x 3 (composed of 4-byte integer elements), 
# also print the shape, type and data type of the array.

a=np.array([[1,2,3],[4,5,6]],dtype='i4')
print(a.shape)
print(type(a))
print(a.dtype)

In [ ]:
#38. Write a NumPy program to create a new shape to an array without changing its data.

a=np.arange(6)
print(a.reshape(2,3))
print(a.reshape(3,2))
a

In [ ]:
#39. Write a NumPy program to change the data type of an array.

a=np.array([[1,2,3],[4,5,6]],dtype='i4')
b=a.astype(float)
print(b)
print(b.dtype)

In [ ]:
#40. Write a NumPy program to create a new array of 3*5, filled with 2.

np.repeat(2,15).reshape(3,5)
# np.full((3,5),2)

In [ ]:
#41. Write a NumPy program to create an array of 10's with the same shape and type of an given array.

a=np.arange(4,dtype=np.int64)
np.full_like(a,10)

In [ ]:
#42. Write a NumPy program to create a 3-D array with ones on a diagonal and zeros elsewhere.

np.eye(3)

In [5]:
#43. Write a NumPy program to create a 2-D array whose diagonal equals [4, 5, 6, 8] and 0's elsewhere.

np.diagflat([4,5,6,8])

array([[4, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 8]])

In [ ]:
#44. Write a NumPy program to create a 1-D array going from 0 to 50 and an array from 10 to 50.

print(np.arange(50))
print(np.arange(10,50))

In [ ]:
#45. Write a NumPy program to Create a 1-D array of 30 evenly spaced elements between 2.5. and 6.5, inclusive.

np.linspace(2.5,6.5,30)

In [ ]:
#46. Write a NumPy program to to create a 1-D array of 20 element spaced evenly on a log scale between 2. and 5., exclusive.

np.logspace(2.0,5.0,20,endpoint=False)

In [6]:
#47. Write a NumPy program to create an array which looks like below array.

np.tri(4,3,-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

In [12]:
#48. Write a NumPy program to create an array which looks like below array.

a=np.arange(2,14).reshape(4,3)
np.triu(a,1)

array([[0, 3, 4],
       [0, 0, 7],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
#49. Write a NumPy program to collapse a 3-D array into one dimension array.

a=np.array([[[10,20,30],[20,40,50]]])
a.flatten()

In [ ]:
#50. Write a NumPy program to find the 4th element of a specified array.

a=np.array([[2,4,6],[6,8,10]])
a.flat[3]

In [ ]:
#51. Write a NumPy program to interchange two axes of an array.

a=np.array([[1,2,3]])
np.swapaxes(a,0,1)

In [ ]:
#52. Write a NumPy program to move axes of an array to new positions. Other axes remain in their original order.

a=np.arange(24).reshape(2,3,4)
print(a)
b=np.moveaxis(a,0,-1)
print(b)
print(b.shape)

In [ ]:
#53. Write a NumPy program to move the specified axis backwards, until it lies in a given position.

a=np.ones((2,3,4,5))
np.rollaxis(a,3,1).shape

In [ ]:
#54. Write a NumPy program to convert specified inputs to arrays with at least one dimension.

a=12.0
print(np.atleast_1d(a))
a=np.arange(6).reshape(2,3)
print(np.atleast_1d(a))
print(np.atleast_1d(1,[3,4]))

In [ ]:
#55. Write a NumPy program to view inputs as arrays with at least two dimensions, three dimensions.

print(np.atleast_2d(15))
print(np.atleast_2d(np.arange(4.0).reshape(2,2)))
print(np.atleast_3d(12))
print(np.atleast_3d(np.arange(3)))


In [ ]:
#56. Write a NumPy program to insert a new axis within a 2-D array.

a=np.arange(6).reshape(2,3)
np.expand_dims(a,axis=1).shape

In [ ]:
#57. Write a NumPy program to remove single-dimensional entries from a specified shape.

a=np.arange(12).reshape(4,1,3)
np.squeeze(a)

In [ ]:
#58. Write a NumPy program to concatenate two 2-dimensional arrays.

a=np.array([[0, 1, 3], [5, 7, 9]])
b=np.array([[0, 2, 4], [6, 8, 10]])
np.concatenate((a,b),axis=1)

In [ ]:
#59. Write a NumPy program to convert 1-D arrays as columns into a 2-D array.

a=np.array([10,20,30])
b=np.array([40,50,60])
np.column_stack((a,b))

In [ ]:
#60. Write a NumPy program to convert (in sequence depth wise (along third axis)) two 1-D arrays into a 2-D array.

arr1=np.array([[1,2,3]])
arr2=np.array([[4,5,6]])            
arr=np.dstack((arr1,arr2))
arr

In [22]:
#61. Write a NumPy program to split an array of 14 elements into 3 arrays, each of which has 2, 4, and 8 elements 
# in the original order.

arr=np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
np.split(arr,[2,6])

[array([1, 2]), array([3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12, 13, 14])]

In [27]:
#62. Write a NumPy program to split of an array of shape 4x4 it into two arrays along the second axis.

a = np.arange(16).reshape(4,4)
np.hsplit(a,[2,4])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]]), array([], shape=(4, 0), dtype=int32)]

In [42]:
#63. Write a NumPy program to get the number of nonzero elements in an array.

a = np.array([[0,10,20],[20,30,40]])
np.count_nonzero(a)

5

In [46]:
#64. Write a NumPy program to create a 5x5 matrix with row values ranging from 0 to 4.

a = np.arange(5)
# np.tile(a,5).reshape(5,5)

np.zeros((5,5))+a

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [51]:
#65. Write a NumPy program to test if specified values are present in an array.

x =np.array([[ 1.12, 2., 3.45],[ 2.33, 5.12, 6. ]])
print(2 in x)
print(0 in x)
print(6 in x)
print(2.3 in x)
print(5.12 in x)

True
False
True
False
True


In [63]:
#66. Write a NumPy program to create a vector of size 10 with values ranging from 0 to 1, both excluded.

np.linspace(0,1,12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [70]:
#67. Write a NumPy program to make an array immutable (read-only).

a = np.zeros(6)
a.flags.writeable=False
a[1]=5

ValueError: assignment destination is read-only

In [78]:
#68. Write a NumPy program (using numpy) to sum of all the multiples of 3 or 5 below 100.

a = np.arange(1,100)
sum(a[(a%3==0) | (a%5==0)])

2318

In [86]:
#69. Write a NumPy program to create an array with 10^3 elements.

np.arange(1e3)

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
        22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,
        33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,
        44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,
        55.,  56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,
        66.,  67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,
        77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,
        88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,
        99., 100., 101., 102., 103., 104., 105., 106., 107., 108., 109.,
       110., 111., 112., 113., 114., 115., 116., 117., 118., 119., 120.,
       121., 122., 123., 124., 125., 126., 127., 128., 129., 130., 131.,
       132., 133., 134., 135., 136., 137., 138., 139., 140., 141., 142.,
       143., 144., 145., 146., 147., 148., 149., 15

In [106]:
#70. Write a NumPy program to create display every element of an numpy array.

a = np.arange(12).reshape(3,4)
for i in np.nditer(a):
    print(i,end=' ')

0 1 2 3 4 5 6 7 8 9 10 11 

In [113]:
#71. Write a NumPy program to create and display every element of an numpy array in Fortran order.

a = np.arange(12).reshape(3,4)
for i in np.nditer(a,order='F'):
    print(i,end=' ')
        

0 4 8 1 5 9 2 6 10 3 7 11 

In [115]:
#72. Write a NumPy program to create a 5x5x5 cube of 1's.

np.ones((5,5,5)).astype(int)

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [119]:
#73. Write a NumPy program to create an array of (3, 4) shape, multiply every element value by 3 and display the new array.

a = np.arange(12).reshape(3,4)
# b=a*3
# b

for i in np.nditer(a,op_flags=['readwrite']):
    i*=3
a

array([[ 0,  3,  6,  9],
       [12, 15, 18, 21],
       [24, 27, 30, 33]])

In [129]:
#74. Write a NumPy program to combine a one and a two dimensional array together and display their elements.

a = np.array([0,1,2,3])
b = np.array([[0,1,2,3],[4,5,6,7]])
for i,j in np.nditer([a,b]):
    print('{}:{}'.format(i,j))


0:0
1:1
2:2
3:3
0:4
1:5
2:6
3:7


In [11]:
#75. Write a NumPy program to create an array of zeros and three column types (integer, float, character).

a = np.zeros((2),dtype=('i4,f4,a40'))
new_data=[(1,2,'Newton'),(3,4,'Einstein')]
a[:]=new_data
a

array([(1, 2., b'Newton'), (3, 4., b'Einstein')],
      dtype=[('f0', '<i4'), ('f1', '<f4'), ('f2', 'S40')])

In [36]:
#76. Write a NumPy program to create a function cube which cubes all the elements of an array.

def cube(a):
    it = np.nditer([a,None])
    for i, j in it:
        j[...]=i*i*i
    return it.operands[1]
x = np.array([1,2,3])
print(cube(x))

[ 1  8 27]


In [ ]:
#77. Write a NumPy program to create an array of (3, 4) shape and convert the array elements in smaller chunks.

